module.exports = [
  "dark", // first theme is the default theme
  "light",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
  {
    pinky: {
      primary: "#e63946",
      secondary: "#a8dadc",
      accent: "#1d3557",
      neutral: "#f1faee",
      "base-100": "#FFFFFF",
      info: "#1d3557",
      success: "#18B473",
      warning: "#ee9b00",
      error: "#d00000",
    },
  },
];
